name: build
on:
  pull_request:
    branches:
        - master
  push:
    tags:
    - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable

  test-build-publish-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ""
      TWINE_REPOSITORY_URL: ${{ secrets.TWINE_REPOSITORY_URL }}
      MIN_COVERAGE: 20
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest
        COVERAGE_RESULT=`coverage report | grep TOTAL | awk '{print $NF}' | sed 's/%//g'`
        echo "Coverage: ${COVERAGE_RESULT}"
        if [[ $COVERAGE_RESULT -gt $MIN_COVERAGE ]]; then
            echo ::set-output name=coverage_result::$COVERAGE_RESULT
        else
            echo "#################################################"
            echo "Code coverage below allowed threshold ($COVERAGE_RESULT<$MIN_COVERAGE)"
            exit 1
        fi
    - name: build package
      run: |
        python setup.py bdist bdist_wheel
    - name: Push to fury 
      run: twine upload dist/* --skip-existing
